---
apiVersion: v1
kind: Namespace
metadata:
  name: creditapp
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: creditapp
type: kubernetes.io/dockerconfigjson
data:
  # This will be patched by GitHub Actions workflow
  .dockerconfigjson: PLACEHOLDER_BASE64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditapp
  namespace: creditapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: creditapp
  template:
    metadata:
      labels:
        app: creditapp
    spec:
      containers:
        - name: creditapp
          image: rati9561/creditapplication:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: creditapp
  namespace: creditapp
spec:
  selector:
    app: creditapp
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creditapp-ingress
  namespace: creditapp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: creditapp.rch.crazylazy.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: creditapp
                port:
                  number: 80
