name: Build EXE with jpackage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019  # Use Windows 2019 runner

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build the application JAR
    - name: Build JAR
      run: |
        mvn clean package
        mkdir dist
        copy target\*.jar dist\app.jar

    # Check if JAVA_HOME is correct
    - name: Print JAVA_HOME
      run: echo $Env:JAVA_HOME

    # Create EXE using jpackage
    - name: Create EXE
      run: |
        mkdir dist\output
        $jpackagePath = "$Env:JAVA_HOME\bin\jpackage"
        Write-Host "Using jpackage at: $jpackagePath"
        & $jpackagePath --type exe --input dist --main-jar app.jar --main-class com.example.Main --name MyApp --runtime-image $Env:JAVA_HOME
        dir
        
    # Upload the EXE as an artifact
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: app-exe
        path: D:\a\creditapplication\creditapplication\dist\MyApp.exe
