name: Build EXE with Embedded JRE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Grant execute permissions to Maven Wrapper
    - name: Make mvnw executable
      run: chmod +x ./mvnw

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build the application
    - name: Build JAR
      run: |
        ./mvnw clean package
        mkdir -p dist
        cp target/*.jar dist/app.jar

    # Download JRE for bundling
    - name: Download JRE 17
      run: |
        mkdir -p dist/jre
        curl -L -o openjdk17.zip https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.8.1+1/OpenJDK17U-jre_x64_windows_hotspot_17.0.8.1_1.zip
        unzip openjdk17.zip -d dist/jre_temp
        mv dist/jre_temp/*/* dist/jre
        rm -rf dist/jre_temp

    # Download Launch4j standalone
    - name: Download Launch4j
      run: |
        mkdir -p launch4j
        curl -L -o launch4j.zip https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-linux.tgz/download
        tar -xvf launch4j.zip -C launch4j --strip-components=1

    # Fix line endings for Launch4j script
    - name: Convert line endings
      run: |
        sed -i 's/\r$//' launch4j/launch4j
        chmod +x launch4j/launch4j

    # Use Launch4j to create EXE
    - name: Create EXE
      run: |
        echo '<launch4jConfig>
          <jar>dist/app.jar</jar>
          <outfile>dist/app.exe</outfile>
          <bundledJrePath>dist/jre</bundledJrePath>
          <bundledJre64Bit>true</bundledJre64Bit>
          <minVersion>17</minVersion>
          <maxVersion>17</maxVersion>
        </launch4jConfig>' > launch4j-config.xml
        ./launch4j/launch4j launch4j-config.xml

    # Upload the EXE as an artifact
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: app-exe
        path: dist/app.exe
