name: Build EXE with Embedded JRE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build the application
    - name: Build JAR
      run: |
        ./mvnw clean package
        mkdir -p dist
        cp target/*.jar dist/app.jar

    # Download JRE for bundling
    - name: Download JRE 17
      run: |
        mkdir -p dist/jre
        curl -L -o openjdk17.tar.gz https://download.java.net/java/GA/jdk17/latest/binaries/openjdk-17_windows-x64_bin.tar.gz
        tar -xvf openjdk17.tar.gz --strip-components=1 -C dist/jre

    # Use Launch4j to create EXE
    - name: Install Launch4j
      run: |
        sudo apt-get update
        sudo apt-get install -y launch4j

    - name: Create EXE
      run: |
        echo '<launch4jConfig>
          <jar>dist/app.jar</jar>
          <outfile>dist/app.exe</outfile>
          <jrePath>dist/jre</jrePath>
          <minVersion>17</minVersion>
          <maxVersion>17</maxVersion>
        </launch4jConfig>' > launch4j-config.xml
        launch4j launch4j-config.xml

    # Upload the EXE as an artifact
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: app-exe
        path: dist/app.exe
